# Generated by Django 3.2.19 on 2024-10-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('features', 'Features'), ('opinion', 'Opinion'), ('creative', 'Creative')], max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
