# Generated by Django 3.2.19 on 2024-10-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='epapers/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
