# Generated by Django 3.2.19 on 2024-10-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_epaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
