# Generated by Django 3.2.19 on 2024-10-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20241012_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
