# Generated by Django 3.2.19 on 2024-10-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
